name: Responsiveness Action

on: [push, issues]

jobs:
  responsiveness_job:
    runs-on: ubuntu-latest
    name: Check responsiveness score of repo
    steps:
      - name: Responsiveness calculation and output
        id: responsiveness
        uses: jadelyyy/hci-bot-responsiveness@v1.3.7
        with:
          repo-token: '1d621c5fa4383ae3416f5120490a5e98d68ed688'
          number-of-months: 1
          repo-name: "hci-bot-demo"

