name: Responsiveness Action

on: [push, issues]

jobs:
  responsiveness_job:
    runs-on: ubuntu-latest
    name: Check responsiveness score of repo
    steps:
      - name: Responsiveness calculation and output
        id: responsiveness
        uses: jadelyyy/hci-bot-responsiveness@v1.9.12
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          additional-token: ${{ secrets.ADDITIONAL_TOKEN }}
          number-of-months: 1
          repo-name: "hci-bot-demo"

